application: rowdy-bot
version: 1-2
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
- url: /_ah/remote_api
  script: _go_app
  login: admin

# Update remotely and learning locally
- url: /(update|learn)
  script: _go_app

- url: .*
  script: _go_app
  login: admin

skip_files:
- go_appengine
- \..*
- README.md
- toolbelt.sh
- backups
- bulkloader*
